defmodule Bedrock.Repo.TenantMigrations.AddBaseline do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:baselines, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :entity_type, :text, null: false
      add :entity_ref, :text, null: false
      add :metric, :text, null: false
      add :count, :bigint, null: false
      add :mean, :float, null: false
      add :stddev, :float, null: false
      add :samples, {:array, :float}, null: false, default: []

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:baselines, [:entity_type, :entity_ref, :metric],
             name: "baselines_unique_baseline_index"
           )
  end

  def down do
    drop_if_exists unique_index(:baselines, [:entity_type, :entity_ref, :metric],
                     name: "baselines_unique_baseline_index"
                   )

    drop table(:baselines, prefix: prefix())
  end
end
