defmodule Bedrock.Repo.TenantMigrations.AddCaseDismissalReason do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:cases, prefix: prefix()) do
      add :dismissal_reason, :text
    end
  end

  def down do
    alter table(:cases, prefix: prefix()) do
      remove :dismissal_reason
    end
  end
end
