defmodule Bedrock.Repo.TenantMigrations.AddCaseSubject do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:cases, prefix: prefix()) do
      add :subject, :text
    end
  end

  def down do
    alter table(:cases, prefix: prefix()) do
      remove :subject
    end
  end
end
