defmodule Bedrock.Repo.TenantMigrations.AddAiNarrativeContextWeaver do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:cases, prefix: prefix()) do
      add :narrative_woven_at, :utc_datetime_usec
    end

    create table(:ai_narratives, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :summary, :text, null: false
      add :machine_generated, :boolean, null: false, default: true
      add :model, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :case_id,
          references(:cases,
            column: :id,
            name: "ai_narratives_case_id_fkey",
            type: :uuid,
            prefix: prefix()
          ), null: false
    end
  end

  def down do
    drop constraint(:ai_narratives, "ai_narratives_case_id_fkey")

    drop table(:ai_narratives, prefix: prefix())

    alter table(:cases, prefix: prefix()) do
      remove :narrative_woven_at
    end
  end
end
