defmodule Bedrock.Repo.TenantMigrations.AddAnomaly do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:anomalies, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :anomaly_type, :text, null: false
      add :score, :bigint, null: false
      add :reason, :text, null: false
      add :entity_ref, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :case_id,
          references(:cases,
            column: :id,
            name: "anomalies_case_id_fkey",
            type: :uuid,
            prefix: prefix()
          ), null: false
    end
  end

  def down do
    drop constraint(:anomalies, "anomalies_case_id_fkey")

    drop table(:anomalies, prefix: prefix())
  end
end
