defmodule Bedrock.Repo.TenantMigrations.AddFindingIdempotency do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:process_instances, [:po_ref],
             name: "process_instances_unique_po_ref_index"
           )

    alter table(:cases, prefix: prefix()) do
      add :finding_type, :text
      add :finding_key, :text
    end
  end

  def down do
    alter table(:cases, prefix: prefix()) do
      remove :finding_key
      remove :finding_type
    end

    drop_if_exists unique_index(:process_instances, [:po_ref],
                     name: "process_instances_unique_po_ref_index"
                   )
  end
end
