defmodule Bedrock.Repo.TenantMigrations.AddComplianceDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:violations, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :control_name, :text, null: false
      add :reason, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :case_id, :uuid, null: false
    end

    create table(:hard_evidence, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :snapshot, :map, null: false

      add :captured_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :case_id, :uuid, null: false
    end

    create table(:connections, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false
      add :odoo_url, :text, null: false
      add :last_synced_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :encrypted_credential, :binary, null: false
    end

    create table(:cases, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:violations, prefix: prefix()) do
      modify :case_id,
             references(:cases,
               column: :id,
               name: "violations_case_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:hard_evidence, prefix: prefix()) do
      modify :case_id,
             references(:cases,
               column: :id,
               name: "hard_evidence_case_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:cases, prefix: prefix()) do
      add :title, :text, null: false
      add :status, :text, null: false, default: "open"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:cases, prefix: prefix()) do
      remove :updated_at
      remove :inserted_at
      remove :status
      remove :title
    end

    drop constraint(:hard_evidence, "hard_evidence_case_id_fkey")

    alter table(:hard_evidence, prefix: prefix()) do
      modify :case_id, :uuid
    end

    drop constraint(:violations, "violations_case_id_fkey")

    alter table(:violations, prefix: prefix()) do
      modify :case_id, :uuid
    end

    drop table(:cases, prefix: prefix())

    drop table(:connections, prefix: prefix())

    drop table(:hard_evidence, prefix: prefix())

    drop table(:violations, prefix: prefix())
  end
end
