defmodule Bedrock.Repo.TenantMigrations.AddControlAlertStats do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:control_alert_stats, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :control_name, :text, null: false
      add :resolved_count, :bigint, null: false, default: 0
      add :actioned_count, :bigint, null: false, default: 0
      add :demoted_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:control_alert_stats, [:control_name],
             name: "control_alert_stats_unique_control_index"
           )
  end

  def down do
    drop_if_exists unique_index(:control_alert_stats, [:control_name],
                     name: "control_alert_stats_unique_control_index"
                   )

    drop table(:control_alert_stats, prefix: prefix())
  end
end
