defmodule Bedrock.Repo.TenantMigrations.AddAlertDeliveryFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:alerts, prefix: prefix()) do
      add :channel, :text, null: false, default: "webhook"
      add :delivery_status, :text, null: false, default: "pending"
      add :delivered_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:alerts, prefix: prefix()) do
      remove :delivered_at
      remove :delivery_status
      remove :channel
    end
  end
end
