defmodule Bedrock.Repo.TenantMigrations.AddAttestation do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:attestations, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :auditor_id, :uuid, null: false
      add :auditor_email, :text, null: false

      add :attested_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :case_id,
          references(:cases,
            column: :id,
            name: "attestations_case_id_fkey",
            type: :uuid,
            prefix: prefix()
          ), null: false
    end
  end

  def down do
    drop constraint(:attestations, "attestations_case_id_fkey")

    drop table(:attestations, prefix: prefix())
  end
end
