defmodule Bedrock.Repo.TenantMigrations.AlertAnomalyScoreNullableSeverity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:alerts, prefix: prefix()) do
      modify :severity, :text, null: true
      add :anomaly_score, :bigint
    end
  end

  def down do
    alter table(:alerts, prefix: prefix()) do
      remove :anomaly_score
      modify :severity, :text, null: false
    end
  end
end
