defmodule Bedrock.Repo.TenantMigrations.AddSuppressionRules do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:suppression_rules, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :control_name, :text, null: false
      add :subject, :text, null: false
      add :reason, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:suppression_rules, [:control_name, :subject],
             name: "suppression_rules_unique_pattern_index"
           )
  end

  def down do
    drop_if_exists unique_index(:suppression_rules, [:control_name, :subject],
                     name: "suppression_rules_unique_pattern_index"
                   )

    drop table(:suppression_rules, prefix: prefix())
  end
end
