defmodule Bedrock.Repo.TenantMigrations.AddAlertsSlice7 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:alerts, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :severity, :text, null: false
      add :money_at_risk, :money_with_currency

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :case_id,
          references(:cases,
            column: :id,
            name: "alerts_case_id_fkey",
            type: :uuid,
            prefix: prefix()
          ), null: false
    end

    create unique_index(:alerts, [:case_id], name: "alerts_unique_case_index")
  end

  def down do
    drop constraint(:alerts, "alerts_case_id_fkey")

    drop_if_exists unique_index(:alerts, [:case_id], name: "alerts_unique_case_index")

    drop table(:alerts, prefix: prefix())
  end
end
