defmodule Bedrock.Repo.TenantMigrations.AddEventHistory do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:events, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :natural_key, :text, null: false
      add :event_type, :text, null: false
      add :payload, :map, null: false
      add :occurred_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:events, [:natural_key], name: "events_unique_natural_key_index")
  end

  def down do
    drop_if_exists unique_index(:events, [:natural_key], name: "events_unique_natural_key_index")

    drop table(:events, prefix: prefix())
  end
end
