defmodule Bedrock.Repo.TenantMigrations.AddConformanceDeviations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:conformance_deviations, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :kind, :text, null: false
      add :reason, :text, null: false
      add :po_ref, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :case_id,
          references(:cases,
            column: :id,
            name: "conformance_deviations_case_id_fkey",
            type: :uuid,
            prefix: prefix()
          ), null: false
    end
  end

  def down do
    drop constraint(:conformance_deviations, "conformance_deviations_case_id_fkey")

    drop table(:conformance_deviations, prefix: prefix())
  end
end
