import Config
config :ash, policies: [show_policy_breakdowns?: true]

config :bedrock, Bedrock.Vault,
  ciphers: [
    default:
      {Cloak.Ciphers.AES.GCM,
       tag: "AES.GCM.V1", key: Base.decode64!("ct8Cyj0o1gjjN8HtTk10k4GKq8oDY54FWlxJ5Cdzj70=")}
  ]

# Configure your database
config :bedrock, Bedrock.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "bedrock_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :bedrock, BedrockWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "SbJY1HpWJNjQnTNj/1SHthOnyY1Yi51Po5cBfBye9/q8vnlK3vADXWfU3rJ5uJWf",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:bedrock, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:bedrock, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :bedrock, BedrockWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/bedrock_web/router\.ex$"E,
      ~r"lib/bedrock_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :bedrock,
  dev_routes: true,
  token_signing_secret: "dDdoGTb4CSaeagV06Re7hZ103zH3x1Ev",
  oauth2_issuer_url: "http://localhost:4000",
  oauth2_resource_url: "http://localhost:4000",
  oauth2_signing_secret: "XiJ7Xr4urfJyk5WTQlc/mip+MkOASqpPiNEW9CRSfb0"

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
