defmodule Bedrock.Repo.Migrations.AddAlertsSlice7 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:organizations) do
      add :materiality_floor, :money_with_currency, null: false
    end
  end

  def down do
    alter table(:organizations) do
      remove :materiality_floor
    end
  end
end
